---
- name: "ensure cert-manager exists on cluster"
  import_role:
    name: "common/k8s-apply"
  vars:
    namespace: "{{ cert_manager.namespace }}"
    template:
      - cert-manager.yaml.j2
      - cluster-issuers.yaml.j2
